language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y tidy
  - cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
